/**
 *  check-wasm-integrity.ts
 *
 *  Asserts that the base64 WASM inlined into src/meshup-js-binary.ts is byte-identical
 *  to src/wasm/meshup_bg.wasm.
 *
 *  Both files are generated by `pnpm build:wasm` and both are committed, so they can
 *  drift apart if one is regenerated or reverted without the other. That drift is
 *  invisible at runtime (the base64 is the only thing actually loaded) until behaviour
 *  silently regresses. This check is cheap and needs no Rust toolchain, so CI can run
 *  it on every push, unlike a full wasm-pack rebuild.
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT_DIR = path.resolve(path.dirname('.'));
const BINARY_TS_PATH = path.join(ROOT_DIR, 'src', 'meshup-js-binary.ts');
const WASM_PATH = path.join(ROOT_DIR, 'src', 'wasm', 'meshup_bg.wasm');

const sha256 = (buf: Uint8Array): string => crypto.createHash('sha256').update(buf).digest('hex');

const source = fs.readFileSync(BINARY_TS_PATH, 'utf8');
const match = source.match(/WASM_BASE64\s*=\s*"([A-Za-z0-9+/=]*)"/);

if (!match)
{
    console.error(`❌ Could not find the WASM_BASE64 string literal in ${BINARY_TS_PATH}`);
    process.exit(1);
}

const inlined = Buffer.from(match[1], 'base64');
const onDisk = fs.readFileSync(WASM_PATH);

const inlinedHash = sha256(inlined);
const onDiskHash = sha256(onDisk);

if (inlinedHash !== onDiskHash)
{
    console.error(`❌ WASM integrity check FAILED — src/meshup-js-binary.ts and src/wasm/meshup_bg.wasm disagree.

    inlined base64 : ${inlinedHash}  (${inlined.length} bytes)
    meshup_bg.wasm : ${onDiskHash}  (${onDisk.length} bytes)

    Re-run \`pnpm build:wasm\` and commit both files together.`);
    process.exit(1);
}

console.log(`✅ WASM integrity OK — ${(onDisk.length / 1024 / 1024).toFixed(2)} MB, sha256 ${onDiskHash.slice(0, 16)}…`);
