//// GLOBAL SETTINGS ////

export const TESSELATION_TOLERANCE = 1e-3; 

export const SHAPES_SPHERE_SEGMENTS_WIDTH = 32;
export const SHAPES_SPHERE_SEGMENTS_HEIGHT = 16;
export const SHAPES_CYLINDER_SEGMENTS_RADIAL = 32;

